baseURL            = "https://www.jaegertracing.io"
title              = "Jaeger: open source, end-to-end distributed tracing"
languageCode       = "en"
pygmentsCodeFences = true
pygmentsUseClasses = true
disableKinds       = ["taxonomy", "taxonomyTerm"]
canonifyURLs       = true
theme              = "jaeger-docs"

[mediaTypes."text/netlify"]
delimiter = ""

[outputFormats.REDIRECTS]
mediaType = "text/netlify"
baseName = "_redirects"

[outputs]
home = [ "HTML", "REDIRECTS" ]

[params]
  tagline = "Monitor and troubleshoot transactions in complex distributed systems"
  githubRepo     = "jaegertracing/jaeger"
  twitterHandle  = "JaegerTracing"
  mediumHandle   = "jaegertracing"
  gitterHandle   = "jaegertracing"
  openGraphImage = "img/jaeger-icon-color.png"
  newsletterTitle = "July 2018 project update"
  newsletterURL   = "https://medium.com/jaegertracing/july-2018-newsletter-71acb4087ecb"

  [navbar]
    [[links]]
      title = "Docs"
      url = "/docs"

[params.versions]
latest = "1.6"