baseURL            = "https://www.jaegertracing.io"
title              = "Jaeger: open source, end-to-end distributed tracing"
languageCode       = "en"
pygmentsCodeFences = true
pygmentsUseClasses = true
disableKinds       = ["taxonomy", "taxonomyTerm"]
canonifyURLs       = true
theme              = "jaeger-docs"

# Disable content taxonomies for now (until there is significantly more content)
#[taxonomies]
#  tag = "tags"

[params]
  tagline = "Monitor and troubleshoot transactions in complex distributed systems"
  githubRepo     = "jaegertracing/jaeger"
  twitterHandle  = "JaegerTracing"
  mediumHandle   = "jaegertracing"
  gitterHandle   = "jaegertracing"
  openGraphImage = "img/jaeger-icon-color.png"
  newsletterTitle = "July 2018 project update"
  newsletterURL   = "https://medium.com/jaegertracing/july-2018-newsletter-71acb4087ecb"

  [navbar]
    [[links]]
      title = "Docs"
      url = "/docs"
