baseURL            = "https://www.jaegertracing.io"
title              = "Jaeger: open source, end-to-end distributed tracing"
languageCode       = "en"
pygmentsCodeFences = true
pygmentsUseClasses = true
disableKinds       = ["taxonomy", "taxonomyTerm"]
canonifyURLs       = true
theme              = "jaeger-docs"
googleAnalytics    = "UA-148208642-1"

[mediaTypes."text/netlify"]
delimiter = ""

[outputFormats.REDIRECTS]
mediaType = "text/netlify"
baseName = "_redirects"

[outputs]
home = [ "HTML", "JSON", "REDIRECTS" ]

[params]
  tagline = "Monitor and troubleshoot transactions in complex distributed systems"
  githubrepo     = "jaegertracing/jaeger"
  twitterhandle  = "JaegerTracing"
  mediumhandle   = "jaegertracing"
  opengraphimage = "img/jaeger-icon-color.png"

  latest = "1.28"
  binariesLatest = "1.28.0"
  versions = ["1.28","1.27","1.26","1.25","1.24","1.23","1.22","1.21","1.20","1.19","1.18","1.17","1.16","1.15","1.14","1.13","1.12","1.11", "1.10", "1.9", "1.8", "1.7", "1.6"]

  [navbar]
    [[links]]
      title = "Docs"
      url = "/docs"

