baseURL            = "https://www.jaegertracing.io"
title              = "Jaeger: open source, end-to-end distributed tracing"
languageCode       = "en"
pygmentsCodeFences = true
pygmentsUseClasses = true
disableKinds       = ["taxonomy", "taxonomyTerm"]
canonifyURLs       = true
theme              = "jaeger-docs"
googleAnalytics    = "UA-148208642-1"

[mediaTypes."text/netlify"]
delimiter = ""

[outputFormats.REDIRECTS]
mediaType = "text/netlify"
baseName = "_redirects"

[outputs]
home = [ "HTML", "JSON", "REDIRECTS" ]

[params]
  tagline = "Monitor and troubleshoot transactions in complex distributed systems"
  githubrepo     = "jaegertracing/jaeger"
  twitterhandle  = "JaegerTracing"
  mediumhandle   = "jaegertracing"
  opengraphimage = "img/jaeger-icon-color.png"

  latest = "1.43"
  binariesLatest = "1.43.0"
  versions = ["1.43","1.42","1.41","1.40","1.39","1.38","1.37","1.36","1.35","1.34","1.33","1.32"]

  [navbar]
    [[links]]
      title = "Docs"
      url = "/docs"
