site_name: Jaeger Documentation
edit_uri: edit/master/docs/
theme_dir: docs/theme
markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
site_favicon: 'images/favicon.ico'
repo_name: 'jaegertracing/documentation'
repo_url: 'https://github.com/jaegertracing/documentation'
extra:
  logo: 'images/jaeger-logo.png'
google_analytics:
  - 'UA-97254222-1'
  - 'auto'
pages: 
  - 'Introduction': 'index.md'
  - 'Getting Started' : 'getting_started.md'
  - 'Features' : 'features.md'
  - 'Client Libraries' : 'client_libraries.md'
  - 'Architecture' : 'architecture.md'
  - 'Deployment' : 'deployment.md'
  - 'Monitoring' : 'monitoring.md'
  - 'Roadmap' : 'roadmap.md'
  - 'News' : 'news.md'
